version: "3.9"

services:
  web:
    build: .
    container_name: myproject
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret
      - ALLOWED_HOSTS=*

